General:
    TOKEN: "" # Your Discord Bot
    ACTIVITY: "watching" # playing, listening, watching, competing, or streaming.
    DOING_ACTIVITY: "Members" # what you want the bot to be playing, listening, watching, competiting, or streaming.
    STREAMING_ACTIVITY_TWITCH_URL: "" # if streaming is chosen, this is the Twitch URL the bot it streaming.
    STATUS: "online" # online, idle, dnd, or invisible.

Schedule:
    SCHEDULE_CHANNEL_ID: 1057122082149892166 # the channel the scheduled message gets sent to.
    SCHEDULE_SECONDS_TIME: 30 # how long should the schedule message should be sent
    SCHEDULE_MESSAGE: "testing stuff :D" # what you want the schedule message to say